### ISSUE TITLE
Question on how you implemented something

### ISSUE THREAD

**Issue by tneotia** [open-imcore/barcelona#27]
Apologies if this is not the ideal place to post something like this, but I was unable to reach you on Discord. I've been devving with BlueBubbles for a bit and recently I started upgrading the helper bundle it has to support Big Sur and new functionalities. Barcelona has been an excellent resource, and many thanks for making it open source and documented!

So I've been stuck on sending attachments via `IMCore`. This is the code I was able to come up with:

```objective-c
        NSArray *eventDataArr = [eventData componentsSeparatedByString:(@",")];
        IMChat *chat = [BlueBubblesHelper getChat: eventDataArr[0]];
        NSString *guid = [[IMFileTransferCenter sharedInstance] guidForNewOutgoingTransferWithLocalURL:([NSURL URLWithString:(eventDataArr[1])])];
        IMFileTransfer *transfer = [[IMFileTransferCenter sharedInstance] transferForGUID:(guid)];
        transfer.transferredFilename = eventDataArr[2];
        transfer.localPath = eventDataArr[1];
        transfer.localURL = [NSURL URLWithString:(eventDataArr[1])];
        [[IMFileTransferCenter sharedInstance] registerGUID:(transfer.guid) forNewOutgoingTransferWithLocalURL:(transfer.localURL)];
        [[IMFileTransferCenter sharedInstance] sendTransfer:(transfer)];
        IMMessage *messageToSend = [[IMMessage alloc] init];
        messageToSend = [messageToSend initWithSender:(nil) fileTransfer:(transfer)];
        messageToSend.flags = 100005;
        [chat sendMessage:(messageToSend)];
```

The `eventDataArr` simply holds the chat guid, the attachment path, and the filename. The transfer seems to go through and the message with the attachment "sends", but it actually gets stuck in a loop of trying to send for a while and then eventually fails. One interesting thing is that images dont show up as the image but rather show the preview app icon with the filename and size, similar to the issues when sending attachments via applescript on Monterey.

Do you see anything that might be off in that code? A lot of it is based off your code so maybe I missed something.

**Comment by EricRabil** [comment]
You are registering your transfer differently and are not setting `shouldForceArchive` to true. See [CBInitializeFileTransfer](https://github.com/open-imcore/barcelona/blob/c10c2cdb9f4c099366f34a4f515876082d6b61ed/Core/Barcelona/Wrappers/Core/Attachment.swift#L152-L164)

**Comment by tneotia** [comment]
I edited the code a bit to match yours but its still the same result:

```objective-c
        IMChat *chat = [BlueBubblesHelper getChat: data[@"chatGuid"]];
        NSString *guid = [[IMFileTransferCenter sharedInstance] guidForNewOutgoingTransferWithLocalURL:([NSURL URLWithString:(data[@"attachment"])])];
        IMFileTransfer *transfer = [[IMFileTransferCenter sharedInstance] transferForGUID:(guid)];
        transfer.transferredFilename = data[@"filename"];
        [[IMFileTransferCenter sharedInstance] registerTransferWithDaemon:(guid)];
        transfer.shouldForceArchive = true;
        [[IMFileTransferCenter sharedInstance] sendTransfer:(transfer)];
        IMMessage *messageToSend = [[IMMessage alloc] init];
        messageToSend = [messageToSend initWithSender:(nil) fileTransfer:(transfer)];
        messageToSend.flags = 100005;
        [chat sendMessage:(messageToSend)];
```

where `data["attachment"]` is a path such as `/Users/tanay/Desktop/Simulator Screen Shot - iPad Pro (12.9-inch) (4th generation) - 2020-09-08 at 15.37.58.png` and `data["filename"]` is the filename `Simulator Screen Shot - iPad Pro (12.9-inch) (4th generation) - 2020-09-08 at 15.37.58.png`. Is there something else I'm missing?

I see this still:

![image](https://user-images.githubusercontent.com/50850142/139913116-8c95a63a-56a8-4a25-b071-10133fe08c39.png)

**Comment by EricRabil** [comment]
Not sure what you're missing them, I'd check logging output of imagent and IMDPersistenceAgent and make sure you've got the correct entitlements and security environment to communicate with them.

**Comment by tneotia** [comment]
Apologies, I'm a bit of a noob when it comes to this stuff if I'm being honest. How exactly would I go about verifying all this? 

It would be strange if I didn't have permissions to communicate since SIP is disabled and MacForge injects the bundle code correctly (sending regular texts, tapbacks, etc all work).
