### ISSUE TITLE
"Could not copy messages from IMDPersistance."

### ISSUE THREAD

**Issue by pkulak** [open-imcore/barcelona#28]
I'm trying to use this with mautrix-imessage, but I keep getting the above error logged, and a list of valid-looking GUIDs, which pretty much shuts everything down. I'm certain I have SIP and AMFI disabled, which means I'm out of ideas. Any help greatly appreciated, thanks!

EDIT: Sorry, Big Sur and XCode 13.

**Comment by pkulak** [comment]
Sure thing:

[trace2.txt](https://github.com/open-imcore/barcelona/files/7406504/trace2.txt)

**Comment by EricRabil** [comment]
@pkulak sorry, just realized this got dropped from the repo. [com.apple.security.xpc.plist](https://github.com/open-imcore/barcelona/raw/mautrix/com.apple.security.xpc.plist) must be installed to `/Library/Preferences/com.apple.security.xpc.plist`, which tells the system to allow Barcelona to communicate with IMDPersistenceAgent.

**Comment by pkulak** [comment]
Thank you so much! That did it.
